databases:
  - name: dpg-cdi085un6mpue9hln8v0-a
    databaseName: project_3_render_db
    user: project_3_render_db_user

services:
  - type: web
    name: Spin_n_Stone
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Spin_n_Stone.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Spin_n_Stone
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4