databases:
  - name: spinnstone
    databaseName: spinnstone
    user: spinnstone

services:
  - type: web
    name: Spin_n_Stone
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Spin_n_Stone.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Spin_n_Stone
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4